EMPTY_PLAYER_PARSED_DATA = {
    "pdga_number": None,
    "crawl_datetime": None,
    "parse_datetime": None,
    "status_code": None,
    "failed_data_points": [],
    "player_name": None,
    "player_location": None,
    "player_location_href": None,
    "player_classification": None,
    "player_member_since": None,
    "player_membership_status": None,
    "player_membership_status_expiration_date": None,
    "player_official_status": None,
    "player_official_status_expiration_date": None,
    "player_current_rating": None,
    "player_current_rating_date": None,
    "player_career_events_singles": None,
    "player_singles_wins": None,
    "player_career_earnings": None,
    "player_upcoming_events": [],
    "player_years_played": [],
    "player_picture_url": None
}
